library(POE5Rdata)
library(plm)
library(broom)
library(knitr)
library(car)
library(AER)
#a
data('klein',package='POE5Rdata')
data=klein[-1,]
total_wage=data$w1+data$w2
lm_a=lm(cn~total_wage+p+plag,data=data)
sum_a=summary(lm_a)
#b
lm_b=lm(w1~plag+klag+w2+g+tx+time+elag,data=data)
sum_b=summary(lm_b)
#c
lm_c=lm(p~plag+klag+w2+g+tx+time+elag,data=data)
sum_c=summary(lm_c)
#d
v1=lm_b$residuals
v2=lm_c$residuals
lm_d=lm(cn~total_wage+p+plag+v1+v2,data=data)
sum_d=summary(lm_d)
summary(lm_d)
f_test=linearHypothesis(lm_d, c("v1=0","v2=0"))
critical_value_d=qf(0.95,2,15)
#e
w1hat=fitted(lm_b)
phat=fitted(lm_c)
lm_e=ivreg(cn~total_wage+p+plag|plag+klag+w2+g+tx+time+elag,data=data)
sum_e=summary(lm_e)
critical_value_e=qt(0.95,17)
#f
ehat=lm_e$residuals
lm_f=lm(ehat~plag+klag+w2+g+tx+time+elag,data=data)
sum_f=summary(lm_f)
r_squared=sum_f$r.squared
test_statistic=21*r_squared
critical_value_f=qchisq(0.95,3)
