#(e)
library(AER)
library(systemfit)
library(POE5Rdata)
data=mroz
#定義變量
lfp=mroz$lfp
mroz_work=mroz[lfp==1,]
wage=mroz_work$wage
ln_wage=log(wage)
educ=mroz_work$educ
age=mroz_work$age
kidsl6=mroz_work$kidsl6
kids618=mroz_work$kids618
faminc=mroz_work$faminc
hours=mroz_work$hours
nwifeinc=faminc-wage*hours
exper=mroz_work$exper
#第一階段迴歸
first_stage<-lm(ln_wage~educ+age+kidsl6+kids618+nwifeinc+exper,data=morz_work)
summary(first_stage)
#擷取EXPER的t統計量和f分數
t_value=summary(first_stage)$coefficients["exper","t value"]
f_stat=t_value^2

#(f)
#做2SLS迴歸,先定義方程式
eq<-hours~ln_wage+educ+age+kidsl6+kids618+nwifeinc
inst<-~educ+age+kidsl6+kids618+nwifeinc+exper
fit<-systemfit(eq,method="2SLS",inst=inst,data=mroz_work)
summary(fit)
